# Generated by Django 4.0.3 on 2022-04-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproducts', '0006_addtocart_is_product_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='member_email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='member_mno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
