# Generated by Django 4.0.3 on 2022-03-29 15:31

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_from', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('product_details', tinymce.models.HTMLField()),
                ('product_price', models.CharField(max_length=10)),
                ('product_image', models.FileField(default=None, max_length=250, null=True, upload_to='products/')),
                ('product_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True)),
                ('product_create_date', models.DateTimeField(auto_now_add=True)),
                ('product_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
