# Generated by Django 4.0.3 on 2022-04-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproducts', '0002_ouramazingteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name_holder', models.CharField(max_length=50)),
                ('member_email', models.CharField(max_length=70)),
                ('member_mno', models.CharField(max_length=15)),
                ('product_id', models.CharField(max_length=10)),
                ('product_slug', models.CharField(max_length=50)),
                ('product_quantity', models.CharField(max_length=5)),
            ],
        ),
    ]
