# Generated by Django 4.0.3 on 2022-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproducts', '0007_alter_addtocart_member_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name_holder', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=10)),
                ('client_name', models.CharField(max_length=50)),
                ('client_loginby', models.CharField(max_length=35)),
                ('client_username', models.CharField(max_length=35)),
                ('client_password', models.CharField(max_length=35)),
                ('client_login_date', models.DateTimeField(auto_now=True)),
                ('client_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name_holder', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('client_email', models.CharField(max_length=35)),
                ('client_mno', models.CharField(max_length=15)),
                ('client_address', models.CharField(max_length=100)),
                ('client_areapincode', models.CharField(max_length=10)),
                ('client_signin_date', models.DateTimeField(auto_now_add=True)),
                ('client_username', models.CharField(max_length=35)),
                ('client_password', models.CharField(max_length=35)),
            ],
        ),
    ]
