# Generated by Django 4.0.3 on 2022-04-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproducts', '0008_login_signin'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='client_five_varification_codes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='signin',
            name='client_varificationby',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
