# Generated by Django 4.0.3 on 2022-04-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproducts', '0005_addtocart_is_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='is_product_delivered',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
